// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from './application';

import AddressesController from './addresses_controller';

application.register('addresses', AddressesController);
